name = "cfvless_tunnel_worker"
main = "src/worker.js"
compatibility_date = "2023-12-18"
workers_dev = true

[vars]
UUID = "0648919d-8bf1-4d4c-8525-36cf487506ec" # 它优先于worker.js中的userID
SOCKS5 = ""                                   # 它优先于worker.js中的socks5Address，同时也优先于下面的PROXYIP
PROXYIP = ""                                  # 它优先于worker.js中的proxyIP
DOH_URL = ""                                  # 它优先于worker.js中的dohURL
CONFIG_PASSWORD = ""                          # 查看节点的配置信息的密码，留空则公开， 所有人都能看到
SUB_PASSWORD = ""                             # 查看节点的订阅内容的密码，留空则公开， 所有人都能看到
GITHUB_TOKEN = ""                             # GitHub访问令牌，用于授权请求
GITHUB_OWNER = ""                             # GitHub仓库所有者的用户名
GITHUB_REPO = ""                              # GitHub私有文件所在的仓库名称
GITHUB_BRANCH = "main"                        # GitHub私有文件所在的分支名称
GITHUB_FILE_PATH = "yx.txt"                   # GitHub私有文件路径(相对路径)，例如：README、yx.txt、cf/yx.txt等
